### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by carlosaicrag** [gnm668/Tub-tub#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by carlosaicrag** [comment]
<img width="604" alt="Screen Shot 2019-11-13 at 9 29 56 AM" src="https://user-images.githubusercontent.com/30717440/68788762-e29a1b00-05f8-11ea-92f4-dd3d4c179741.png">
email is a little funky on here

**Comment by carlosaicrag** [comment]
<img width="557" alt="Screen Shot 2019-11-13 at 9 31 20 AM" src="https://user-images.githubusercontent.com/30717440/68788788-ef1e7380-05f8-11ea-93e2-19c646cb8c6f.png">
the signup boxes could be style a little better so their positioning isnt awkward

**Comment by carlosaicrag** [comment]
lets put a button thats redirects you to the home page from either the login page or sign up page.  Also i would put the guest login button on the login page not the signup page.

**Comment by gnm668** [comment]
I made my login and sign up into modals so that you have access to the homepage at all times, and I also made my 404 page with a redirect back to my homepage. 

Do you want me to leave the guest sign in on my sign up page as well, or only my login? Should I put it on both pages of my login?

**Comment by carlosaicrag** [comment]
I think the login should be in the page where the email is but it shoudl not be in the signup page
